# Generated by Django 2.2.4 on 2022-10-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0002_tree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
