# Generated by Django 2.2.4 on 2022-10-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0003_delete_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Species', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('dateplann', models.DateTimeField(auto_now_add=True)),
                ('visitors', models.CharField(max_length=45)),
                ('planted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trees', to='m_app.User')),
                ('users', models.ManyToManyField(related_name='trees', to='m_app.User')),
            ],
        ),
    ]
